// SPEC-0015 PLAN-0041 Worker Behavior Parity Gate
//
// This is the release-blocker E2E test that asserts the public
// simulation wizard's UI flow produces a worker artifact set
// (corners-annotated dots, dimension-guide lines, sofa bounding-box
// centroid) within tolerance of the terminal-harness baseline. The
// terminal harness was validated against the canonical pipeline on
// 2026-04-29; the gate exists to catch UI-side regressions — most
// likely from the client-side compression step — before the wizard
// ships.
//
// The test is gated on the RUN_PARITY_GATE environment variable so
// regular CI does not burn OpenAI credits or assume a live worker is
// running. The intended workflow:
//
// 1. Start the local Supabase stack and the in-home simulation worker
//    (see docs/local-supabase-worker-development.md).
// 2. Drop a real room photo into
//    scripts/seed-simulation-test-data/fixtures/parity-room.jpg and
//    a baseline coordinate set into
//    scripts/seed-simulation-test-data/fixtures/parity-baseline.json.
//    The current files in this repository are placeholders.
// 3. Boot the Next.js dev server.
// 4. Run `RUN_PARITY_GATE=1 pnpm --filter @mobel-unique/web exec
//    vitest run apps/web/src/__tests__/parity-gate.e2e.test.ts`.
//
// The baseline is regenerated by re-running the terminal harness with
// the same fixture and recording dot/line/centroid coordinates from
// the artifact bytes. The exact regeneration command is documented
// in docs/local-supabase-worker-development.md.

import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = resolve(
  HERE,
  "../../../../scripts/seed-simulation-test-data/fixtures"
);
const FIXTURE_ROOM = resolve(FIXTURES_DIR, "parity-room.jpg");
const BASELINE_PATH = resolve(FIXTURES_DIR, "parity-baseline.json");

const RUN_GATE = process.env.RUN_PARITY_GATE === "1";

interface ParityBaseline {
  version: string;
  geometry_mode: "back_wall" | "corner";
  tolerance: {
    dot_position_px: number;
    line_position_px: number;
    centroid_position_px: number;
  };
  stage_1_corners: {
    image_width_px: number;
    image_height_px: number;
    expected_dots: Array<{ label: string; x: number; y: number }>;
  };
  stage_1_dimension_guide: {
    image_width_px: number;
    image_height_px: number;
    expected_lines: Record<string, number>;
  };
  stage_2_result: {
    image_width_px: number;
    image_height_px: number;
    expected_sofa_centroid: { x: number; y: number };
  };
}

function loadBaseline(): ParityBaseline {
  const raw = readFileSync(BASELINE_PATH, "utf8");
  return JSON.parse(raw) as ParityBaseline;
}

describe("Worker Behavior Parity Gate (release blocker)", () => {
  it("baseline file structure stays in sync with the terminal harness contract", () => {
    const baseline = loadBaseline();
    expect(baseline.geometry_mode === "back_wall" || baseline.geometry_mode === "corner").toBe(true);
    expect(typeof baseline.tolerance.dot_position_px).toBe("number");
    expect(typeof baseline.tolerance.line_position_px).toBe("number");
    expect(typeof baseline.tolerance.centroid_position_px).toBe("number");
    expect(Array.isArray(baseline.stage_1_corners.expected_dots)).toBe(true);
    expect(typeof baseline.stage_2_result.expected_sofa_centroid.x).toBe("number");
    expect(typeof baseline.stage_2_result.expected_sofa_centroid.y).toBe("number");
  });

  it.skipIf(!RUN_GATE)(
    "uploads parity-room.jpg through the UI flow and asserts dot/line/centroid positions against baseline within tolerance",
    async () => {
      // The implementation of this gate consumes the live worker. It
      // is intentionally absent from the repository until PLAN-0042
      // wires the production worker to the canonical pipeline.
      //
      // The flow this gate must perform when activated:
      //
      //   const fixture = readFileSync(FIXTURE_ROOM);
      //   const baseline = loadBaseline();
      //   const accessToken = await mintLocalAccessToken();
      //   const job = await postUploadAgainstLiveBackend({
      //     fixture,
      //     accessToken,
      //     sofaSlug: "simulation-test-back-wall",
      //     fabricId: "...",
      //     visualPositionId: "..."
      //   });
      //   await waitForStatus(job.simulation_job_id, "succeeded", { timeoutMs: 600_000 });
      //   const dots = await downloadCornersAnnotatedArtifact(job);
      //   const lines = await downloadDimensionGuideArtifact(job);
      //   const centroid = await measureSofaCentroidInResult(job);
      //   assertWithinTolerance(dots, baseline.stage_1_corners.expected_dots,
      //                         baseline.tolerance.dot_position_px);
      //   assertWithinTolerance(lines, baseline.stage_1_dimension_guide.expected_lines,
      //                         baseline.tolerance.line_position_px);
      //   assertWithinTolerance(centroid, baseline.stage_2_result.expected_sofa_centroid,
      //                         baseline.tolerance.centroid_position_px);
      //
      // If any tolerance fails, the prime suspect is the client-side
      // compression step (see PLAN-0041 notes). Raise JPEG quality to
      // 0.95 or skip compression for files under 5 MB before
      // declaring the plan done.
      expect(FIXTURE_ROOM).toMatch(/parity-room\.jpg$/);
      throw new Error(
        "Parity gate activation pending PLAN-0042 production worker migration"
      );
    }
  );
});
